fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     App\Entity\User
    group:
        group_class:   App\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager


    from_email:
        address:        '%env(MAILER_ADDRESS)%'
        sender_name:    '%env(MAILER_NAME)%'