sonata_admin:
    title: 'Sonata Admin'
    title_logo: bundles/sonataadmin/logo_title_xl.png
    options:
        title_mode: single_image # One of "single_text"; "single_image"; "both"
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
